sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- cd ./build
- docker-compose build
- echo "TRAVIS_TAG="$TRAVIS_TAG;
- echo "TRAVIS_BRANCH="$TRAVIS_BRANCH;
- echo "MagicMirror_Version="$MagicMirror_Version;
# push image
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";    
- docker push $DOCKER_USER/magicmirror:$TRAVIS_BRANCH;
